# Generated by Django 4.0.4 on 2022-07-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_book_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='portrait',
            field=models.URLField(blank=True, null=True),
        ),
    ]
