# Generated by Django 4.0.4 on 2022-07-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_author_portrait'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-timestamp']},
        ),
    ]
